Release 1.0.32
yearn/yearn-finance-v3 pull request #575
Opened 2022-04-01 19:01 UTC by xgambitox

- Add windows dev env instructions
- Fix console warnings on modals
- Add tests to formatters utils
- Add yvBoost metedata overrides
- Add estimated earnings and estimated yearly yield for Labs

2022-04-03 03:11 UTC, karelianpie requested changes
"Add yvBoost metedata overrides" might need to wait until we decide on the cache approach

2022-04-04 19:55 UTC, turtlemoji approved these changes

2022-04-04 20:43 UTC, FiboApe approved these changes

2022-04-04 21:58 UTC, turtlemoji approved these changes

2022-04-04 22:16 UTC, FoxTheSin approved these changes
difference from fibo's last approve until now*

2022-04-04 22:23 UTC, karelianpie approved these changes

2022-04-04 22:29 UTC, merged